apiVersion: v1
kind: Secret
metadata:
  name: app2
stringData:
  USERNAME: app2login
  PASSWORD: S0methingS@Str0ng!

---
#Secret with encoded data

apiVersion: v1
kind: Secret
metadata:
  name: app3
data:
  USERNAME: YXBwMmxvZ2lu
  PASSWORD: UzBtZXRoaW5nU0BTdHIwbmch

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data:
  db-password: ZGJwYXNzd29yZDEx